--- #YAML:1.1
language: python
cache: pip
python:
    - "2.7"
env:
    - DB=postgres
before_script:
    - psql -c 'create database collectr;' -U postgres
notifications:
    irc:
        channels: "irc.freenode.org#linkuist"
        on_success: always
        on_failure: always

install:
    - "pip install pip --upgrade"
    - "pip install -r requirements/base.txt"
    - "pip install -r requirements/2nd-pass.txt"
    - "pip install -r requirements/tests.txt"
    - "yes | pip uninstall South || true"
    - "pip install coveralls"
script:
    - "cd collectr"
    - "python manage.py syncdb --settings=settings_travis --noinput"
    - "python manage.py migrate --settings=settings_travis"
    - "coverage run manage.py test source --settings=settings_travis collector source userprofile link_tracking semantism webfront"
services:
    - redis-server
after_success:
    - coveralls
