--- #YAML:1.1
language: python
cache: pip
python:
    - "2.7"
env:
    - DB=postgres

install:
    - "pip install pip --upgrade"
    - "pip install -r requirements/base.txt"
    - "pip install -r requirements/2nd-pass.txt"
    - "pip install -r requirements/tests.txt"
    - "pip install coveralls"

before_script:
    - psql -c 'create database collectr;' -U postgres

script:
    - "coverage run manage.py test --settings='collectr.settings_travis'"

services:
    - redis-server

after_success:
    - coveralls

notifications:
    irc:
        channels: "irc.freenode.org#linkuist"
        on_success: always
        on_failure: always
